### ISSUE TITLE
Optimal-rtb Code

### ISSUE THREAD

**Issue by mpearmain** [wnzhang/optimal-rtb#2]
Are you still intending to release the optimal rtb code?

**Comment by wnzhang** [comment]
Sorry. Super busy recently. I will add it ASAP. The ORTB function itself is quite simple, the important thing is the parameter tuning :)

**Comment by mpearmain** [comment]
I was just looking at your new pid controller function. Very cool

**Comment by wnzhang** [comment]
Thanks. It is for a paper submission still under review.. so I had better not discuss too much on that. If you check rtbarbitrage repository, ORTB algorithm has been uploaded there :)
